name: bergagna
favicon: null
layout_spectrum: 0.49308
typography_spectrum: 0.50632
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#75cdd9'
    - '#868686'
    - '#5e5e5e'
    - '#373737'
  brandStrength: 0.028475106693804264
  lightness: 0.3777232216671109
  saturation: 0.01358920824714005
  rhythmicContrast: 0.2585483400616795
purpose: []
